schemaVersion: '2.0.0'
commandTests:
- name: 'Python Version is 3.11'
  command: 'python'
  args: ['--version']
  expectedOutput: ['Python 3.11.*']
fileExistenceTests:
- name: 'Virtual Environment exists under /app/venv'
  path: '/app/venv'
  shouldExist: true
  permissions: 'drwxr-xr-x'
  uid: 0
  gid: 0
  isExecutableBy: 'group'
