schemaVersion: '2.0.0'
commandTests:
- name: 'Python Version is 3.11'
  command: 'python'
  args: ['--version']
  expectedOutput: ['Python 3.11.*']
- name: 'Ensure Poetry is not installed'
  command: 'poetry'
  args: ['--version']
  expectedError: ['.*poetry: not found.*']
- name: 'Ensure dev dependencies are not installed'
  command: 'python'
  args: ['-c', 'import pytest']
  expectedError: ['.*ModuleNotFoundError.*']

fileExistenceTests:
- name: 'Virtual Environment exists under /app/venv'
  path: '/app/venv'
  shouldExist: true
  permissions: 'drwxr-xr-x'
  uid: 0
  gid: 0
  isExecutableBy: 'group'
