apiVersion: v1
kind: Service
metadata:
  name: autograder-service
  namespace: github-action-runner
spec:
  type: ClusterIP
  selector:
    app: autograder
  ports:
  - port: 8000
    targetPort: 8000
